substandardApartment-V2/FE

src/App.scss
src/components/News/NewsFooter/NewsPagination.module.scss
src/components/News/NewsFooter/NewsPagination.tsx
src/components/News/NewsHeader/NewsHeader.tsx
src/components/News/NewsHeader/NewsHeaderTab.tsx
src/components/News/NewsMain/NewsItem.tsx
src/components/News/NewsMain/NewsMain.tsx
src/pages/News.module.scss
src/pages/News.tsx

> 절대경로로 변경
> 뉴스관련 파일의 경로들을 절대경로로 변경하였습니다

[feat] 경로 변경

---

.gitignore
src/pages/Report.tsx
src/pages/report.module.scss

> #15
> 제보 페이지 UI 구현
> 제보 페이지 퍼블리싱 완료했습니다
env 파일 만들었습니다!
> VITE_GOOGLE_URL=https://docs.google.com/forms/d/1vma-OGQDkCYLmeZCxx_2z6CqTPFpTGF9q-7wtiYWG3c/edit

[feat] 제보 퍼블리싱 완료

---

.github/workflows/build.yml
src/components/News/NewsHeader/NewsHeader.tsx

> main 브랜치로 변경
> CI/CD Develop에서 main으로 변경

[refactor] 브랜치 main으로 변경

---

.github/workflows/build.yml

[refactor] 환경변수 처리 방법 변경

---

.github/workflows/build.yml
src/components/Header.module.scss
src/components/News/NewsFooter/NewsPagination.module.scss
src/components/News/NewsHeader/NewsHeader.module.scss
src/components/News/NewsMain/NewsMain.module.scss
src/styles/_colors.scss

> x
> 컬러 정의를 위한 SCSS 파일 추가 및 @use로 공통 사용
> 컬러 변수 정의를 위한 _colors.scss 파일 추가 및 다른 SCSS 파일에서 @use로 공통 사용하도록 수정

[style] 컬러 정의를 위한 SCSS 파일 추가 및 @use로 공통 사용

---

src/App.scss
src/components/Header.module.scss
src/components/News/NewsHeader/NewsHeader.module.scss
src/components/News/NewsMain/NewsMain.module.scss

> #7
> 뉴스 간격 수정 
> 뉴스 헤더 아래 간격 조절

[style] 뉴스 css 수정

---

src/Router.tsx
src/components/Error/NotFound.tsx

> #32
> 404 에러 처리 페이지 만들었습니다
> Not found 컴포넌트를 생성 후 잘못된 경로 페이지 처리
디자인 나오면 추후 디자인 적용하겠습니다

[feat] 에러 컴포넌트 생성

---

src/hooks/search/useSearhRecord.ts

> #48
> 최근 검색어 커스텀 훅 정의
> 검색어 추가, 특정 검색어 삭제, 전체삭제 함수 커스텀 훅으로 정의하였습니다.

[feat] 최근 검색어 커스텀 훅 정의

---

src/components/WeakApart/WholeWeakApartInfo/DetailWeakRankInfo.module.scss
src/components/WeakApart/WholeWeakApartInfo/WeakApartInfo.module.scss

> #36
> 부실아파트 관련 디자인 에러 수정
> 부실아파트 정보 사이 선 디자인 수정하였습니다.
> 스크롤 문제 수정하였습니다.

[style] 부실아파트 정보 디자인 수정

---

src/components/Common/ApartSearch/ApartSearch.tsx
src/components/Common/ApartSearch/ApartSearchInput.tsx
src/components/Common/ApartSearch/ApartSearchResult.tsx
src/components/Main/ApartInfo/ApartMainInfo/ApartMaintanceCharge.module.scss
src/components/Main/ApartInfo/ApartMainInfo/ApartMaintanceCharge.tsx
src/components/Main/Chart/MaintanceChargeChart.tsx
src/components/WeakApart/Chart/FiveYearsWeakBuilderChart.tsx
src/hooks/Api/useGetSearchData.ts
src/types/TWeak/TWeakApartInfoTypes.ts
src/utils/api/getSearchData.ts
src/utils/mapping/WeakApartInfo.ts

> #36
> 지도 검색 api 커스텀 훅 분리
> 타입 에러 수장
> 지도 검색 api 호출 커스텀 훅으로 분리하였습니다.
> 부실아파트 데이터 타입 에러 수정하였습니다.

[feat] 지도 검색 커스텀 흑 분리

---

src/components/Common/ApartSearch/ApartSearchResult.tsx
src/components/Common/ApartSearch/ApartSearchResultItem.tsx

> #55
> 컴포넌트 분리
> 검색 결과 컴포넌트 분리했습니다

[feat] 검색 결과 컴포넌트 분리

---

index.html
public/script/MarkerClustering.js
src/components/Common/ApartSearch/ApartSearchInput.tsx
src/components/Common/ApartSearch/ApartSearchResult.tsx
src/components/Common/ApartSearch/ApartSearchResultItem.tsx
src/components/Header/NavList.tsx
src/components/Main/ApartInfo/ApartInfo.tsx
src/components/Main/ApartInfo/ApartMainInfo/ApartBuildInfo/ApartBuildInfoList.tsx
src/components/Main/ApartInfo/ApartMainInfo/ApartGeneralInfo/ApartAmenitiesInfo.tsx
src/components/Main/ApartInfo/DetailMaintanceCharge.tsx
src/components/Main/ApartMap/ApartMap.tsx
src/components/Main/WholeApartInfo/ServiceNotice/ServiceNotice.tsx
src/components/WeakApart/WeakMainNews/WeakMainNews.tsx
src/hooks/Api/useGetApartMarker.ts
src/hooks/Api/useGetNewsData.ts
src/hooks/Api/useGetSearchData.ts
src/hooks/Map/useCreateCluster.ts
src/hooks/Map/useMapMarkers.ts
src/hooks/Search/useInfinityScroll.ts
src/hooks/Search/useSearhRecord.ts
src/store/useMarkerStore.ts
tsconfig.app.json

> #63
> 지도 관련 이슈 수정
> setMarkerData 오타 수정
> 중복 set함수 수정
> useInfiniteScroll 요청으로 API 콜 통합
> "정보 보기" 누를 시 마커 이벤트 핸들러 등록
> localStorage 저장 이슈 해결

[fix] 지도 관련 이슈 수정

---

src/components/Common/ApartSearch/ApartSearchResultItem.tsx
src/hooks/Map/useCreateCluster.ts

> 클러스터 디자인 변경
> 정보보기 위치 이동
> 지도 클러스터 디자인 변경했습니다
> 검색 결과 정보보기 클릭 시 해당 위치로 이동

[feat] 지도 클러스터 디자인 변경 및 정보보기 이슈 해결

---

src/components/News/NewsFooter/NewsPagination.module.scss
src/components/News/NewsFooter/NewsPagination.tsx
src/components/News/NewsMain/NewsMain.tsx
src/components/News/NewsMain/Skeleton/NewsSkeleton.module.scss

> #39 
> 뉴스 이슈 사항 수정
> 뉴스 페이지네이션 간격, 크기 수정
> 뉴스 스켈레톤 높이 수정

[feat] 뉴스 이슈 사항 수정

---

src/components/Common/ApartSearch/ApartSearchInput.module.scss
src/components/Common/ApartSearch/ApartSearchInput.tsx
src/components/Common/ApartSearch/ApartSearchResultItem.tsx
src/components/Header/Header.module.scss
src/components/Header/Header.tsx
src/components/Header/NavList.tsx
src/components/Main/ApartInfo/ApartHeadInfo.tsx
src/components/Main/ApartMap/ApartLocation.tsx
src/components/Main/ApartMap/ApartMap.tsx
src/components/Main/WholeApartInfo/CurrentApartsStatus/CurrentApartsStatus.tsx
src/components/Main/WholeApartInfo/CurrentApartsStatus/StatusList.module.scss
src/components/Main/WholeApartInfo/CurrentApartsStatus/StatusList.tsx
src/components/News/NewsMain/NewsList.tsx
src/components/WeakApart/Chart/DetailWeakBuilderChart.tsx
src/hooks/Api/useGetApartData.ts
src/hooks/Api/useGetPageData.ts
src/hooks/Api/useGetSearchData.ts
src/hooks/Map/useCreateMap.ts
src/hooks/Map/useLocationPath.ts
src/hooks/Map/useMapMarkers.ts
src/hooks/Search/useInfinityScroll.ts
src/store/useMarkerStore.ts
src/types/TApi/TAPITypes.ts
src/types/TMain/TCurrentApartsStatusListTypes.ts
src/utils/mapping/MainInfo.ts
src/utils/parse/fotmatPriceCurrency.ts

> #73
> 배포 이슈 수정
> 검색 결과 리스트 "정보 보기" 클릭 마커 색 변화 적용
> 메인 페이지 변경 API 연결
> 초기 지도 로딩 시 input 입력 비활성화
> 건설사 하자판정 건수 순위 라벨 스타일 에러
> 헤더 border-bottom 조건 부 스타일
> 동일 위도, 경도 "현 지도에서 검색" 이벤트 핸들러 미작동
위 배포 이슈 수정하였습니다!

Fix/release error fix#73

---

src/components/Common/ApartSearch/ApartSearchInput.tsx
src/components/Header/Header.tsx
src/components/Header/NavList.tsx
src/components/Main/ApartInfo/ApartMainInfo/ApartBuildInfo/ApartBuildInfo.module.scss
src/components/Main/ApartInfo/ApartMainInfo/ApartBuildInfo/ApartBuildInfoList.module.scss
src/components/Main/ApartMap/ApartMap.tsx
src/components/Main/WholeApartInfo/ServiceNotice/ServiceNotice.module.scss
src/components/Main/WholeApartInfo/ServiceNotice/ServiceNoticeList.module.scss
src/components/WeakApart/WeakMainNews/WeakMainNewsList.module.scss
src/hooks/Map/useCreateMap.ts

> #73
> 배포 에러 수정
> 네이버 지도 렌더링 이슈 수정
> 부실아파트 페이지 뉴스 폰트 스타일 변경
> 일반아파트 건설정보 스타일 깨지는 이슈 수정
> 탭간 전환할때 마커 유지되는 이슈 수정

[fix] 배포 에러 이슈 수정

---

src/components/Error/NotFound.tsx
src/components/Main/WholeApartInfo/CurrentApartsStatus/StatusList.module.scss
src/components/Main/WholeApartInfo/ServiceNotice/ServiceNotice.module.scss
src/components/WeakApart/WeakMainNews/WeakMainNewsList.module.scss

> 간단한 css 수정
> 이미지 비율 수정
> 메인 폰트 수정 및 굵기 추가

[style] 폰트 수정 및 이미지 비율 수정

---

src/components/Common/ApartSearch/ApartSearchInput.tsx
src/components/Common/ApartSearch/ApartSearchResultItem.tsx
src/hooks/Api/useGetApartMarker.ts
src/hooks/Map/useMapMarkers.ts
src/hooks/Search/useInfinityScroll.ts

>  #73
> 선택 마커 색 변화 수정
> 검색한 아파트 리스트 "정보보기"누를 시 마커 렌더링 안하는 이슈 수정하였습니다.
> 이와 연관된 인피니티 스크롤 위도,경도 이동 기존 로직 수정 후 PR올리도록 하겠습니다.

[fix] 선택 마커 스타일 변화 수정 #73

---

src/components/Common/ApartSearch/ApartSearchResultItem.tsx

> #73
> 마커 선택 마커 이미지 변화 로직 수정
> 기존의 setTimeout로직에서 새롭게 마커를 그리는 방식으로 변경하였습니다.

[fix] 마커 변화 로직 수정 #73

---

src/components/Common/ApartSearch/ApartSearchResult.tsx
src/components/Common/ApartSearch/ApartSearchResultItem.tsx
src/hooks/Search/useInfinityScroll.ts
src/store/useMarkerStore.ts
src/store/useSearchStore.ts

> #73
> 검색으로 인한 결과 리스트 수정
> 아파트 검색 후 "정보보기"클릭 시 마커 아이콘 변하지 않는 문제 수정하였습니다.
> 인피니티 스크롤 page상태 및 이전 검색 상태 추가하였습니다.

[fix] 아파트 검색 인피니티 스크롤 이슈 수정

---

src/hooks/Map/useMapMarkers.ts

> #73
> 검색 마커 클릭 이슈 수정
> 검색 마커 클릭 후 마커 사라지는 이슈 수정하였습니다.

[fix] 검색 후 마커 클릭 사라짐 이슈 수정#73

---

src/components/Common/ApartSearch/ApartRecentSearchList.tsx
src/components/Common/ApartSearch/ApartSearchResultItem.tsx
src/hooks/Api/useGetSearchData.ts
src/hooks/Search/useInfinityScroll.ts

> #73
>  최근 검색어 리스트 클릭 시 마커 사람짐 이슈
> 최근 검색어 리스트 클릭 시 마커 사라지는 이슈 수정 하였습니다.
> 기존의 useGetApartData를 InfiniteScroll훅 호출로 변경하였습니다.

[fix] 최근 검색어 마커 렌더링 이슈 수정#73

---

src/hooks/Search/useInfinityScroll.ts

> #73
> 아파트 검색 조건 추가
> 아파트 검색 -> 정보보기 -> 동일한 아파트 검색 api호출 시 조건문 추가하였습니다.

[fix] 검색 api 호출 조건 추가#73

---

src/components/Common/ApartSearch/ApartSearchResultItem.tsx
src/components/Header/NavList.tsx

> #73
> NavLink set함수 추가
> 아파트 검색 결과 리스트 초기화 상태변수 set함수 트리거 정의하였습니다

[fix] NavLink set함수 추가#73
